[package]
name = "lnchannels"
version = "0.1.0"
authors = ["fiatjaf <fiatjaf@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
reqwest = "0.9.17"
serde_json = "1.0"
serde = "1.0.91"
rusqlite = "0.18.0"
